name: Auto Assign
on:
  pull_request:
    types: [opened, ready_for_review]
jobs:
  add-reviews:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    name: Assign users to Pull Requests
    steps:
      - uses: kentaro-m/auto-assign-action@v2.0.0
        with:
          configuration-path: '.github/config/auto-assign.yml'
